<script setup>
import { computed, ref } from 'vue'

const props = defineProps({ overview: { type: Object, required: true }, busy: { type: Boolean, default: false } })
const emit = defineEmits(['refresh', 'role'])
const tab = ref('overview')
const search = ref('')
const people = computed(() => props.overview.users.filter((person) => `${person.name} ${person.email} ${person.organization}`.toLowerCase().includes(search.value.toLowerCase())))
const roles = { admin: 'Администратор', business: 'Бизнес', team: 'Команда' }
const operation = { analysis: 'Разбор задачи', interview: 'AI-интервью', handoff: 'Handoff Test' }
function date(value) { return value ? new Date(value).toLocaleString('ru-RU', { dateStyle: 'short', timeStyle: 'short' }) : '—' }
function money(value) { return value == null ? '—' : `$${Number(value).toFixed(5)}` }
function requestRole(person, event) { const role = event.target.value; event.target.value = person.role; emit('role', person, role) }
</script>

<template>
  <div class="page admin-page">
    <div class="admin-hero"><div><span class="eyebrow">FORGE / CONTROL CENTER</span><h1>Всё важное —<br><em>под контролем.</em></h1><p>Управляйте доступом и отслеживайте работу платформы. Затраты AI рассчитаны по записанным токенам и тарифу модели.</p><div class="admin-hero-actions"><span :class="['admin-live', { off: !overview.ai_configured }]">{{ overview.ai_configured ? '● OpenAI подключён' : '● OpenAI не настроен' }}</span><span>Модель: {{ overview.model }}</span></div></div><button class="button button-ghost" :disabled="busy" @click="emit('refresh')">↻ Обновить данные</button></div>

    <div class="admin-tabs" role="tablist" aria-label="Разделы панели администратора"><button v-for="item in [['overview','Обзор'],['users','Пользователи и роли'],['usage','AI и токены'],['audit','История ролей']]" :key="item[0]" :class="{ active: tab === item[0] }" role="tab" :aria-selected="tab === item[0]" @click="tab = item[0]">{{ item[1] }}</button></div>

    <template v-if="tab === 'overview'"><div class="admin-stats"><article><span>Пользователи</span><strong>{{ overview.stats.users }}</strong><small>{{ overview.stats.businesses }} бизнес · {{ overview.stats.teams }} команд</small></article><article><span>Задачи</span><strong>{{ overview.stats.tasks }}</strong><small>{{ overview.stats.published }} опубликовано</small></article><article><span>Отклики</span><strong>{{ overview.stats.proposals }}</strong><small>{{ overview.stats.pending_proposals }} ждут решения</small></article><article><span>AI-запросы</span><strong>{{ overview.usage.calls }}</strong><small>{{ overview.usage.failed_calls }} с ошибкой</small></article></div><div class="admin-overview-grid"><section class="admin-feature"><span class="eyebrow">РАСХОДЫ AI</span><h2>{{ money(overview.usage.estimated_cost_usd) }}</h2><p>Оценка в USD за зарегистрированные вызовы с известным тарифом. Не равна счёту в OpenAI.</p><div class="admin-token-split"><span>Входящие <b>{{ overview.usage.input_tokens.toLocaleString('ru-RU') }}</b></span><span>Кэшированные <b>{{ overview.usage.cached_input_tokens.toLocaleString('ru-RU') }}</b></span><span>Исходящие <b>{{ overview.usage.output_tokens.toLocaleString('ru-RU') }}</b></span></div><small v-if="overview.usage.unpriced_calls">{{ overview.usage.unpriced_calls }} вызовов без известного тарифа не включены в сумму.</small></section><section class="admin-feature admin-feature-image"><span class="eyebrow">РАБОЧИЙ КОНТУР</span><h2>Идея →<br>ясная задача.</h2><p>Все действия сохраняются в одной системе: от брифа до предложения команды.</p></section></div></template>

    <template v-else-if="tab === 'users'"><div class="admin-section-head"><div><h2>Пользователи и роли</h2><p>Роль меняется сразу. Последнего администратора снять нельзя.</p></div><input v-model="search" type="search" aria-label="Поиск пользователей" placeholder="Найти по имени, почте, организации" /></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Пользователь</th><th>Организация</th><th>Роль</th><th>Задачи</th><th>AI-вызовы</th><th>Регистрация</th></tr></thead><tbody><tr v-for="person in people" :key="person.id"><td><strong>{{ person.name }}</strong><small>{{ person.email }}</small></td><td>{{ person.organization }}</td><td><select :value="person.role" :disabled="busy" :aria-label="`Роль ${person.email}`" @change="requestRole(person, $event)"><option v-for="(label, role) in roles" :key="role" :value="role">{{ label }}</option></select></td><td>{{ person.tasks_count }}</td><td>{{ person.ai_calls }}</td><td>{{ date(person.created_at) }}</td></tr></tbody></table><div v-if="!people.length" class="admin-empty">Пользователи не найдены.</div></div></template>

    <template v-else-if="tab === 'usage'"><div class="admin-section-head"><div><h2>Использование OpenAI</h2><p>Фактические токены из ответов API; стоимость — локальная оценка. Старые вызовы до внедрения журнала здесь не появятся.</p></div></div><div class="admin-mini-stats"><div><span>Запросы</span><strong>{{ overview.usage.calls }}</strong></div><div><span>Всего токенов</span><strong>{{ (overview.usage.input_tokens + overview.usage.output_tokens).toLocaleString('ru-RU') }}</strong></div><div><span>Оценка</span><strong>{{ money(overview.usage.estimated_cost_usd) }}</strong></div></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Время</th><th>Операция / пользователь</th><th>Модель</th><th>Вход / кэш</th><th>Выход</th><th>Стоимость</th><th>Статус</th></tr></thead><tbody><tr v-for="call in overview.recent_usage" :key="call.id"><td>{{ date(call.created_at) }}</td><td><strong>{{ operation[call.operation] || call.operation }}</strong><small>{{ call.actor_email || 'Системный вызов' }}</small></td><td>{{ call.model }}</td><td>{{ call.input_tokens }} <small>({{ call.cached_input_tokens }} кэш)</small></td><td>{{ call.output_tokens }}</td><td>{{ money(call.estimated_cost_usd) }}</td><td><span :class="['admin-status', call.status]">{{ call.status === 'completed' ? 'Успешно' : 'Ошибка' }}</span></td></tr></tbody></table><div v-if="!overview.recent_usage.length" class="admin-empty">AI-вызовов после включения учёта пока нет.</div></div><p class="admin-footnote">По умолчанию тариф для gpt-4.1-mini: $0.40 / $0.10 кэш / $1.60 за 1 млн токенов. Для другой модели задайте тарифы в .env. Неизвестная стоимость не включается в сумму.</p></template>

    <template v-else><div class="admin-section-head"><div><h2>История изменения ролей</h2><p>Кто и когда выдал доступ. Записи не редактируются через интерфейс.</p></div></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Когда</th><th>Кто изменил</th><th>Пользователь</th><th>Изменение</th></tr></thead><tbody><tr v-for="event in overview.role_audit" :key="event.id"><td>{{ date(event.created_at) }}</td><td>{{ event.actor_email }}</td><td>{{ event.target_email }}</td><td>{{ roles[event.old_role] || event.old_role }} → <strong>{{ roles[event.new_role] || event.new_role }}</strong></td></tr></tbody></table><div v-if="!overview.role_audit.length" class="admin-empty">Изменений ролей пока нет.</div></div></template>
  </div>
</template>
